#!/usr/bin/env python3
"""Pin two local Git revisions and create isolated mobile parity worktrees.

Requires Python 3.9+ and Git. No network requests, dependency installs, checkout
switches, fixture injection, simulator launches, or automatic cleanup occur.
"""

import argparse
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import uuid


class SetupError(Exception):
    pass


def git(repo, *args, check=True, timeout=30):
    env = os.environ.copy()
    env["GIT_OPTIONAL_LOCKS"] = "0"
    env["GIT_TERMINAL_PROMPT"] = "0"
    try:
        result = subprocess.run(
            ["git", "-c", "core.quotepath=false", "-C", str(repo), *args],
            capture_output=True, text=True, env=env, timeout=timeout,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise SetupError(f"Git operation failed in {repo}: {exc}") from exc
    if check and result.returncode:
        detail = result.stderr.strip() or result.stdout.strip()
        raise SetupError(f"Git {' '.join(args[:2])} failed in {repo}: {detail}")
    return result


def inside(path, directory):
    try:
        path.relative_to(directory)
        return True
    except ValueError:
        return False


def inspect_repo(path, ref, branch, output, platform):
    supplied = Path(path).expanduser().resolve()
    root = Path(git(supplied, "rev-parse", "--show-toplevel").stdout.strip()).resolve()
    if not ref.strip() or ref.startswith("-"):
        raise SetupError(f"Invalid {platform} ref: {ref!r}")
    sha = git(root, "rev-parse", "--verify", "--end-of-options", ref + "^{commit}").stdout.strip()
    git(root, "check-ref-format", "--branch", branch)
    collision = git(root, "show-ref", "--verify", "--quiet", "refs/heads/" + branch, check=False)
    if collision.returncode == 0:
        raise SetupError(f"Branch already exists: {branch} in {root}")
    if collision.returncode != 1:
        raise SetupError(f"Could not check branch collision in {root}: {collision.stderr.strip()}")

    # Older macOS Git versions lack worktree-list -z. Porcelain supports spaces.
    worktrees = [root]
    for line in git(root, "worktree", "list", "--porcelain").stdout.splitlines():
        if line.startswith("worktree "):
            worktrees.append(Path(line[len("worktree "):]).resolve())
    common_raw = git(root, "rev-parse", "--git-common-dir").stdout.strip()
    common = Path(common_raw)
    common = (root / common).resolve() if not common.is_absolute() else common.resolve()
    if any(inside(output, tree) for tree in worktrees) or inside(output, common):
        raise SetupError(f"Run output must be outside all {platform} checkouts and Git metadata: {output}")

    source_branch = git(root, "symbolic-ref", "--quiet", "--short", "HEAD", check=False)
    if source_branch.returncode not in (0, 1):
        raise SetupError(f"Could not inspect current branch in {root}")
    return {
        "repo_path": str(root),
        "input_ref": ref,
        "base_sha": sha,
        "source_head": git(root, "rev-parse", "HEAD").stdout.strip(),
        "source_branch": source_branch.stdout.strip() or None,
        "source_dirty": bool(git(root, "status", "--porcelain=v1", "--untracked-files=normal").stdout),
        "uncommitted_included": False,
        "freshness": "not-checked-by-helper",
        "branch": branch,
        "worktree": str(output / "worktrees" / platform),
        "state": "planned",
    }


def write_manifest(path, manifest):
    temporary = path.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    temporary.replace(path)


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ios-repo", required=True)
    parser.add_argument("--ios-ref", required=True, help="Explicit local ref/tag/SHA; fetch separately if needed")
    parser.add_argument("--android-repo", required=True)
    parser.add_argument("--android-ref", required=True)
    parser.add_argument("--reference-platform", required=True, choices=("ios", "android", "bidirectional"))
    parser.add_argument("--reference-reason", required=True, help="Why this is the reference, or why direction is unresolved")
    parser.add_argument("--output", required=True, help="New durable run directory outside both repositories")
    parser.add_argument("--run-id", help="Lowercase letters/digits/hyphens; generated by default")
    parser.add_argument("--branch-prefix", default="michaelboeding/", help="Prefix before parity/<run-id>/<platform>")
    parser.add_argument("--dry-run", action="store_true", help="Print plan without writing files or creating branches")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    now = datetime.now(timezone.utc)
    run_id = args.run_id or (now.strftime("%Y%m%dt%H%M%Sz") + "-" + uuid.uuid4().hex[:6])
    manifest = None
    manifest_path = None
    try:
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]{0,79}", run_id):
            raise SetupError("run-id must be 1–80 lowercase letters, digits, or hyphens, starting with a letter/digit")
        if not args.reference_reason.strip():
            raise SetupError("reference-reason cannot be empty")
        raw_output = Path(args.output).expanduser()
        if raw_output.is_symlink():
            raise SetupError(f"Output cannot be an existing symlink: {raw_output}")
        output = raw_output.resolve()
        if output.exists():
            raise SetupError(f"Output already exists; choose a fresh directory: {output}")
        prefix = args.branch_prefix.rstrip("/")
        branch_base = (prefix + "/" if prefix else "") + "parity/" + run_id

        # Resolve and validate BOTH sides before creating any branch or worktree.
        platforms = {}
        for platform in ("ios", "android"):
            platforms[platform] = inspect_repo(
                getattr(args, platform + "_repo"), getattr(args, platform + "_ref"),
                branch_base + "/" + platform, output, platform,
            )
        manifest = {
            "schema_version": 1,
            "run_id": run_id,
            "created_at": now.isoformat(),
            "focus": "mobile-uiux-parity",
            "status": "planned",
            "reference": {"platform": args.reference_platform, "reason": args.reference_reason.strip()},
            "output_root": str(output),
            "platforms": platforms,
            "notes": [
                "Commit snapshots only; source checkout changes are not copied.",
                "No fetch performed; verify freshness and scope separately.",
                "No apps built/launched and no UI/UX checks executed by this helper.",
            ],
        }
        if args.dry_run:
            print(json.dumps(manifest, indent=2))
            return 0

        output.mkdir(parents=True, exist_ok=False)
        manifest_path = output / "run.json"
        manifest["status"] = "preparing"
        write_manifest(manifest_path, manifest)
        for name in ("worktrees", "fixtures", "evidence", "logs", "patches"):
            (output / name).mkdir()
        for platform, item in platforms.items():
            item["state"] = "creating"
            write_manifest(manifest_path, manifest)
            # -b refuses collisions; no --force, checkout switching, or remote edits.
            git(item["repo_path"], "worktree", "add", "-b", item["branch"], item["worktree"], item["base_sha"], timeout=120)
            actual = git(item["worktree"], "rev-parse", "HEAD").stdout.strip()
            if actual != item["base_sha"]:
                raise SetupError(f"Unexpected {platform} worktree HEAD: {actual}")
            item["state"] = "ready"
            write_manifest(manifest_path, manifest)
        manifest["status"] = "prepared"
        write_manifest(manifest_path, manifest)
        print(f"Prepared audit worktrees. Manifest: {manifest_path}")
        for platform, item in platforms.items():
            print(f"{platform}: {item['branch']} at {item['base_sha']} -> {item['worktree']}")
        return 0
    except (SetupError, OSError, KeyboardInterrupt) as exc:
        error = str(exc) or "Setup interrupted"
        if manifest_path is not None and manifest is not None:
            manifest["status"] = "partial"
            manifest["error"] = error
            for item in manifest["platforms"].values():
                if item["state"] == "creating":
                    item["state"] = "inspect-after-failure"
            try:
                write_manifest(manifest_path, manifest)
            except OSError as write_error:
                print(f"Could not update manifest: {write_error}", file=sys.stderr)
            print(f"Partial setup retained at {manifest_path}; inspect before reusing or removing resources.", file=sys.stderr)
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
